language: node_js
node_js:
  - 10 # use Node 10 LTS or later
before_install:
  - brew install hugo
  - npm install -g @lhci/cli
script:
  - hugo --gc --minify # build your site
  - lhci autorun --rc-overrides.upload.target=temporary-public-storage # run lighthouse CI
addons:
  chrome: stable # make sure you have Chrome available
