name: Lighthouse (Local)
on: [pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.70.0"
          extended: true

      - name: Build site
        run: hugo

      - name: Audit local build using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          configPath: ./lighthouse/lighthouserc.local.js
