name: Lighthouse (Preview)
on: [pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Wait for Netlify
        uses: JakePartusch/wait-for-netlify-action@v1.2
        id: waitFor200
        with:
          site_name: angry-kirby-8b4540

      - name: Audit deploy preview using Lighthouse
        run: |
          sudo npm install -g @lhci/cli@0.4.x
          lhci autorun --config=./.github/lighthouse/lighthouserc.deploy.js --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      # this one may still come in handy for the deploy-preview config
      # - name: Audit URLS using Lighthouse
      #   uses: treosh/lighthouse-ci-action@v2
      #   with:
      #     budgetPath: ./budget.json # test performance budgets
      #     uploadArtifacts: true # save results as an action artifacts
      #     temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      #     configPath: "./lighthouserc.json"
